#language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t wjmk/docker-react -f Dockerfile.dev .

 script: 
  - docker run -e CI=true wjmk/docker-react npm run test -- --coverage